name: Daily News Update

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: write # Required to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::607477397669:role/ByeDonald3Stack-GitHubActionsRole4F1BBA26-11Rv3x2wQC4I
          aws-region: ${{ vars.AWS_REGION }} 

      - name: Fetch latest news
        run: npm run backfill-newsapi.org
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Tag new articles
        run: npm run tag-news

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "feat: daily news update"
          git push

      - name: Build site
        if: steps.git-check.outputs.changes
        run: npm run build

      - name: Deploy to S3
        if: steps.git-check.outputs.changes
        run: |
          aws s3 sync public/ s3://${{ vars.ORIGIN_BUCKET }} --delete
